name: Build and Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup toolchain install stable-x86_64-pc-windows-msvc
          rustup default stable-x86_64-pc-windows-msvc

      - name: Build
        run: cargo build --verbose --target x86_64-pc-windows-msvc
        env:
          CARGO_TERM_COLOR: always

  package:

    needs: build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: rustup toolchain install stable-x86_64-pc-windows-msvc

      - name: Build Release
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Archive Release
        run: |
          mkdir -p artifacts
          cp target/x86_64-pc-windows-msvc/release/vam_downloader.exe artifacts/
        env:
          CARGO_TERM_COLOR: always

      - name: Upload Release
        uses: actions/upload-artifact@v3
        with:
          name: vam_downloader
          path: artifacts/vam_downloader.exe
